### ISSUE TITLE
Recipe-App-Issue

### ISSUE THREAD

**Issue by siddghosh108** [siddghosh108/Recipe-App#1]
Link of the project:
https://github.com/users/siddghosh108/projects/4/views/1
We have two members in our team and they are:
[Siddhartha Ghosh](https://github.com/siddghosh108) and [Nelly Telli](https://github.com/lily4178993)

**Comment by julie-ify** [comment]
## Hi @siddghosh108 and @lily4178993,

Good job so far!

## Highlights!
- Descriptive README ✔️ 

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
- [ ] You are yet to add the In Review column, between In Progress and Done. You should have four columns.

  ![image](https://github.com/siddghosh108/Recipe-App/assets/81468675/f5792c1b-2b04-426e-b727-6c2fb07f7334)

- [ ] All the tasks listed in the guidelines should be created on the kanban board. Kindly ensure all tasks are present. You have only about 4 tasks.

  ![image](https://github.com/siddghosh108/Recipe-App/assets/81468675/d47901cc-87a9-4693-96b7-3bcfc54e94fa)

  ![image](https://github.com/siddghosh108/Recipe-App/assets/81468675/970cebaf-b558-46ea-bf80-efdfcd2b4b7e)

- [ ] Kindly ensure all your tasks have descriptions. See an example of a task with no description.

  ![image](https://github.com/siddghosh108/Recipe-App/assets/81468675/2889598d-a873-43ea-b30a-67a396ead05b)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@julie-ify` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by lily4178993** [comment]
Thank you @julie-ify for your feedback!

**Comment by TedLivist** [comment]
## STATUS: APPROVED ✔️ ✔️

Hi @lily4178993 and @siddghosh108,

✔️ Descriptive tasks

Your project is complete!  There is nothing else to say other than... it's time to go ahead with the project :shipit: 
Congratulations! 🎉

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by lily4178993** [comment]
Thank you @TedLivist for your feedback!
